ui_builder.ui_builder_component.*:
  type: config_entity
  label: 'UI Builder Component'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    layout_tree:
      type: string
      label: 'Layout Tree (JSON)'
    css:
      type: string
      label: 'Custom CSS'
    javascript:
      type: string
      label: 'Custom Javascript'
    form_schema:
      type: string
      label: 'Field Definitions (JSON)'
    uuid:
      type: string

ui_builder.ui_builder_style.*:
  type: config_entity
  label: 'UI Builder Style'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    data:
      type: ignore
      label: 'Style Tree Data'
    uuid:
      type: string
